// autogenerated at 2025-08-07T10:17:56.7446139+00:00

interface IAuthConfirmEmailRequest {
    code: string | null;
    email: string | null;
    analytics?: string | null;
}

interface IAuthLoginRequest {
    username: string | null;
    password: string | null;
    analytics?: string | null;
}

interface IAuthLogoutRequest {
    analytics?: string | null;
}

interface IAuthPasswordResetRequest {
    code: string | null;
    token: string | null;
    email: string | null;
    password: string | null;
    repeat: string | null;
    analytics?: string | null;
    hash?: string | null;
}

interface IAuthPasswordResetResponse {
    code: number | null;
    message: string | null;
}

interface IAuthPasswordResetCodeRequest {
    email: string | null;
    analytics: string | null;
}

interface IAuthPasswordResetStartRequest {
    code: string | null;
    email: string | null;
    token: string | null;
    timezone: string | null;
    analytics?: string | null;
}

interface IAuthRegisterRequest {
    email: string | null;
    password: string | null;
    repeat: string | null;
    analytics?: string | null;
    hash?: string | null;
}

interface IAuthRegisterResponse {
    code: number | null;
    message: string | null;
}

