// This file is auto-generated by the build process. Do not edit it manually.
export const AUTH_MAX_PASSWORD_LENGTH = 72;
export const AUTH_MIN_PASSWORD_LENGTH = 6;
export const AUTH_REQUIRED_UPPERCASE = 1;
export const AUTH_REQUIRED_LOWERCASE = 1;
export const AUTH_REQUIRED_NUMBER = 1;
export const AUTH_REQUIRED_SPECIAL = 1;
export const AUTH_MAX_LOGIN_ATTEMPTS = 5;
