@host=http://0.0.0.0:5000

// function pages.index(
//     _user_id text DEFAULT NULL::text,
//     _build_id text DEFAULT NULL::text
// )
// returns text
//
// comment on function pages.index is 'HTTP GET /
// Content-Type: text/html
// allow-anonymous
// cached _user_id
// parse-response';
GET {{host}}/?userId=ABC&buildId=XYZ

###

