@host=http://0.0.0.0:5000

// function auth.login(
//     _username text,
//     _password text,
//     _data json DEFAULT '{}'::json,
//     _ip_address text DEFAULT NULL::text
// )
// returns record
//
// comment on function auth.login is 'HTTP POST
// Login
// Anonymous';
POST {{host}}/api/auth/login
content-type: application/json

{
    "username": "ABC",
    "password": "XYZ",
    "data": {},
    "ipAddress": "ABC"
}

###

// function auth.register(
//     _email text,
//     _password text,
//     _repeat text
// )
// returns record
//
// comment on function auth.register is 'HTTP POST
// Anonymous';
POST {{host}}/api/auth/register
content-type: application/json

{
    "email": "ABC",
    "password": "XYZ",
    "repeat": "IJK"
}

###

