// autogenerated at 2025-08-01T10:41:40.7014619+00:00

import { baseUrl } from "$lib/urls";
import { parseQuery } from "$lib/urls";

export const todoGetItemsUrl = (request: ITodoGetItemsRequest) => baseUrl + "/api/todo/get-items" + parseQuery(request);

/**
* function todo.get_items(
*     _search text
* )
* returns table(
*     id bigint,
*     title text,
*     completed boolean,
*     user_id bigint
* )
* 
* @remarks
* comment on function todo.get_items is 'HTTP GET
* Authorize';
* 
* @param {ITodoGetItemsRequest} request
* @returns {{status: number, response: ITodoGetItemsResponse[] | string}}
* 
* @see FUNCTION todo.get_items
*/
export async function todoGetItems(
    request: ITodoGetItemsRequest
) : Promise<{status: number, response: ITodoGetItemsResponse[] | string}> {
    const response = await fetch(todoGetItemsUrl(request), {
        method: "GET",
        headers: {
            "Content-Type": "application/json"
        },
    });
    return {
        status: response.status,
        response: response.status == 200 ? await response.json() as ITodoGetItemsResponse[] : await response.text()
    };
}
