// autogenerated at 2025-08-01T10:41:40.6971491+00:00

interface ITodoGetItemsRequest {
    search: string | null;
}

interface ITodoGetItemsResponse {
    id: number | null;
    title: string | null;
    completed: boolean | null;
    userId: number | null;
}

