FROM vbilopav/npgsqlrest:v2.15.0

WORKDIR /app

COPY ./config/npgsqlrest.json ./appsettings.json
COPY ./config/npgsqlrest.dev.json ./npgsqlrest.dev.json

ENTRYPOINT ["npgsqlrest", "appsettings.json", "npgsqlrest.dev.json", "--optional", "npgsqlrest.id.json"]