FROM oven/bun:1.2.8-alpine

WORKDIR /app

COPY ./config/rollup.build.js ./config/rollup.build.js
COPY ./config/rollup.config.js ./config/rollup.config.js
COPY ./config/rollup.shared.js ./config/rollup.shared.js
COPY ./config/postinstall.js ./config/postinstall.js
COPY package*.json ./
COPY tsconfig.json ./
ENV DOCKER=true

RUN bun install --production
