FROM oven/bun:alpine

RUN apk add --no-cache postgresql-client

WORKDIR /app

RUN bun install -g @vbilopav/pgmigrations@0.42.0
COPY ./config/pgmigrations.js ./
COPY ./config/.env ./config/.env
COPY ./backend ./backend
