FROM vbilopav/npgsqlrest:v2.23.0

WORKDIR /app
COPY ./config/npgsqlrest.json ./appsettings.json

# Optional copy of external auth providers json file if it exsists
COPY ./config/external-auth-providers.* ./external-auth-providers.json

ENTRYPOINT ["npgsqlrest", "appsettings.json", "--optional", "external-auth-providers.json"]