FROM vbilopav/npgsqlrest:v2.20.0

WORKDIR /app
COPY ./config/npgsqlrest.json ./appsettings.json
COPY ./config/npgsqlrest.dev.json ./npgsqlrest.dev.json

# Optional copy of external auth providers json file if it exsists
COPY ./config/external-auth-providers.* ./external-auth-providers.json

ENTRYPOINT ["npgsqlrest", "appsettings.json", "--optional", "npgsqlrest.dev.json", "--optional", "external-auth-providers.json"]