const svelte = require("rollup-plugin-svelte");
const commonjs = require("@rollup/plugin-commonjs");
const resolve = require("@rollup/plugin-node-resolve");
const terser = require("@rollup/plugin-terser");
const sveltePreprocess = require("svelte-preprocess");
const typescript = require("@rollup/plugin-typescript");
const css = require("rollup-plugin-css-only");
const sass = require('sass');
const replace = require('@rollup/plugin-replace');
const alias = require("@rollup/plugin-alias");
const tailwindcss = require('@tailwindcss/postcss');
const postcss = require("postcss");
const chokidar = require("chokidar");
const path = require("path");
const fs = require("fs");

const distPath = "./dist";
const assetsPath = "./src/assets";
const styleCss = "./src/style/style.css";
const buildIdFile = "./config/npgsqlrest.id.json";

const distCss = path.join(distPath, path.basename(styleCss)).replace(/\\/g, "/");
const production = !process.env.ROLLUP_WATCH;
const isDocker = process.env.DOCKER === 'true'; 

var chokidarWatchConfig = undefined;
if (isDocker) {
    chokidarWatchConfig = {
        usePolling: true,
        interval: 500,
        awaitWriteFinish: {
            stabilityThreshold: 500,
            pollInterval: 100
        }
    };
}

const d = new Date();
const buildId = "v"+`${d.getFullYear().toString().slice(2)}${(d.getMonth()+1).toString().padStart(2,'0')}${d.getDate().toString().padStart(2,'0')}${d.getHours().toString().padStart(2,'0')}${d.getMinutes().toString().padStart(2,'0')}${d.getSeconds().toString().padStart(2,'0')}${d.getMilliseconds().toString().padStart(3,'0')}`;

const error = msg => console.error("\x1b[31m" + msg + "\x1b[0m");
const warn = msg => console.warn("\x1b[33m" + msg + "\x1b[0m");
const info = msg => console.log("\x1b[36m" + msg + "\x1b[0m");

function cpy(from, to) {
    if (!fs.existsSync(from)) {
        error(`ERROR: Could not find file '${from}'`);
        return;
    }
    if (!fs.existsSync(to)) {
        fs.mkdirSync(path.dirname(to), { recursive: true });
    }
    info(`${from} → ${to}...`);
    if (from.endsWith('.html')) {
        let content = fs.readFileSync(from, 'utf8').replace(/\.css"|\.js"/g, function(match) {
            return match.replace('"', `?${buildId}"`);
        });
        fs.writeFileSync(to, content);
    } else {
        fs.copyFileSync(from, to);
    }
}

function copyAssets(dir) {
    let files = fs.readdirSync(dir);
    for(let i = 0; i < files.length; i++) {
        let file = path.join(dir, files[i]);
        if (fs.statSync(file).isDirectory()){
            copyAssets(file);
        } else {
            let destPath = path.join(distPath, path.relative(assetsPath, dir));
            let dest = path.join(destPath, files[i]);
            cpy(file, dest);
        }
    }
}

function emptyDist() {
    if (!fs.existsSync(distPath)) {
        info(`${distPath} → created ...`);
        fs.mkdirSync(distPath);
    } else {
        const files = fs.readdirSync(distPath);
        for (const file of files) {
            const fullPath = path.join(distPath, file);
            fs.rmSync(fullPath, { recursive: true, force: true });
        }
        info(`${distPath} → cleared ...`);
    }
}

function createNpgsqlBuildIdConfig() {
    fs.writeFileSync(buildIdFile, [
        "// autogenerated by rollup.config.cjs", 
        JSON.stringify({ 
            NpgsqlRest: {
                CustomParameterMappings: {"_build_id": buildId}
            } 
        })
    ].join("\n"));
    info(`${buildIdFile} → created ${buildId} ... `);
}

async function buildTailwindCSS() {
    try {
        const css = fs.readFileSync(styleCss, "utf8");
        const result = await postcss([
            tailwindcss({
                optimize: {
                    minify: production
                }
            }),
        ]).process(css, {
            from: styleCss,
            to: distCss,
            map: false
        });
        fs.writeFileSync(distCss, result.css);
    } catch (err) {
        error(styleCss + ' → ' + distCss + ' → rebuild failed: ' + err);
        return;
    }
    info(styleCss + ' → ' + distCss);
}

function rollupPlugin(options = {}) {
    return {
        name: 'watch-build-end',
        watchChange(id) {
            info('build → ' + "./src/" + id.replace(/\\/g, "/").split("/src/")[1]);
        },
        buildEnd() {
            buildTailwindCSS();
        }
    }
};

function createConfig(input) {
    const appObject = input.split("/").pop().split(".")[0];
    const cssOutput = appObject + ".css";
    return {
        input: input,
        output: {
            sourcemap: !production,
            format: "iife",
            dir: distPath,
            name: appObject,
            globals: {}
        },
        plugins: [
            rollupPlugin(),
            alias({
                entries: [
                    { find: "$api", replacement:  path.resolve(__dirname, "../src/api") },
                    { find: "$lib", replacement:  path.resolve(__dirname, "../src/app/lib") }
                ]
            }),
            replace({
                preventAssignment: true,
                "process.env.NODE_ENV": JSON.stringify("development")
            }),
            typescript({
                sourceMap: !production,
                inlineSources: !production,
                noEmitOnError: !production,
                tsconfig: "tsconfig.json"
            }),
            svelte({
                preprocess: sveltePreprocess({ 
                    sourceMap: !production,
                }),
                compilerOptions: {
                    // enable run-time checks when not in production
                    dev: !production,
                    customElement: false,
                }
            }),
            // we"ll extract any component CSS out into
            // a separate file - better for performance
            css({ 
                output: async function(styles, bundle) {
                    if (production) {
                        fs.writeFileSync(path.join(distPath, cssOutput), sass.compileString(styles, {syntax: "css", style: "compressed"}).css);
                    } else {
                        fs.writeFileSync(path.join(distPath, cssOutput), styles);
                    }
                }
            }),
            // If you have external dependencies installed from
            // npm, you"ll most likely need these plugins. In
            // some cases you"ll need additional configuration -
            // consult the documentation for details:
            // https://github.com/rollup/plugins/tree/master/packages/commonjs
            resolve({
                browser: true,
                dedupe: ["svelte"],
                extensions: [".svelte", ".ts", ".json", ".js"]
            }),
            commonjs({ 
                sourceMap: !production 
            }),

            // If we"re building for production (npm run build
            // instead of npm run watch), minify
            production && terser()
        ],
        onwarn(warning, warn) {
            if (warning.code === 'CIRCULAR_DEPENDENCY') {
                return;
            }
            warn(warning);
        },
        watch: {
            clearScreen: false,
            chokidar: chokidarWatchConfig
        }
    };
}

module.exports = args => {
    if (!args["input"] || args["input"].length === 0) {
        throw new Error('No input file specified! Use "npx rollup --config r./config/rollup.config.cjs [input ts file path or multiple paths] [-w --watch]');
    }

    const inputFiles = [];
    for (const input of args["input"]) {
        if (!fs.existsSync(input)) {
            warn(`Input path does not exist: ${input}`);
            continue;
        }

        if (fs.statSync(input).isDirectory()) {
            const files = fs.readdirSync(input);
            for (const file of files) {
                const fullPath = "./" + path.join(input, file).replace(/\\/g, "/");
                if (!fs.statSync(fullPath).isDirectory() && fullPath.endsWith('.ts')) {
                    inputFiles.push(fullPath);
                } else if (!fs.statSync(fullPath).isDirectory()) {
                    warn(`Skipping non-TypeScript file: ${fullPath}`);
                }
            }
        } else {
            if (input.endsWith('.ts')) {
                inputFiles.push(input);
            } else {
                warn(`Skipping non-TypeScript file: ${input}`);
            }
        }
    }

    if (inputFiles.length === 0) {
        throw new Error("No valid input files found!");
    }

    args["input"] = inputFiles;
    
    emptyDist();
    copyAssets(assetsPath);
    createNpgsqlBuildIdConfig();

    if (!production) {
        chokidar.watch(styleCss, chokidarWatchConfig).on("change", buildTailwindCSS);
        console.log(`[${new Date().toISOString().replace('T', ' ').substring(0, 19)}] watching ${styleCss} for changes...`);
    }

    if (inputFiles.length === 1) {
        return createConfig(inputFiles[0]);
    }

    const result = [];
    for(let i = 0; i < inputFiles.length; i++) {
        result.push(createConfig(inputFiles[i]));
    }

    return result;
}