// autogenerated at 2025-04-17T11:08:45.2838459+00:00
interface IAuthConfirmEmailRequest {
    code: string | null;
    email: string | null;
    analyticsData?: string | null;
    ipAddress?: string | null;
}

interface IAuthLoginRequest {
    username: string | null;
    password: string | null;
    analyticsData?: string | null;
    ipAddress?: string | null;
}

interface IAuthLogoutRequest {
    userId: string | null;
    userName: string | null;
    analyticsData: string | null;
}

interface IAuthPasswordResetRequest {
    code: string | null;
    token: string | null;
    email: string | null;
    password: string | null;
    repeat: string | null;
    analyticsData?: string | null;
    ipAddress?: string | null;
}

interface IAuthPasswordResetResponse {
    code: number | null;
    message: string | null;
}

interface IAuthPasswordResetCodeRequest {
    email: string | null;
    analyticsData: string | null;
    ipAddress?: string | null;
}

interface IAuthPasswordResetStartRequest {
    code: string | null;
    email: string | null;
    token: string | null;
    timezone: string | null;
    analyticsData?: string | null;
    ipAddress?: string | null;
}

interface IAuthRegisterRequest {
    email: string | null;
    password: string | null;
    repeat: string | null;
    analyticsData?: string | null;
    ipAddress?: string | null;
}

interface IAuthRegisterResponse {
    code: number | null;
    message: string | null;
}

